//! Naming conventions for compiler-generated typestate types and handlers.

pub const GENERATED_STATE_PREFIX: &str = "__ts_";
pub const GENERATED_HANDLER_PREFIX: &str = "__ts_on_";

/// Parses a generated handler name to extract the request-site label suffix.
///
/// Generated by typestate lowering:
///   `__ts_on_<ordinal>__site_<label>`
pub fn parse_generated_handler_site_label(method_name: &str) -> Option<&str> {
    let suffix = method_name.strip_prefix(GENERATED_HANDLER_PREFIX)?;
    let (_, label) = suffix.split_once("__site_")?;
    if label.is_empty() {
        return None;
    }
    Some(label)
}
