//! Naming conventions for compiler-generated typestate types and handlers.

pub const GENERATED_STATE_PREFIX: &str = "__ts_";
pub const GENERATED_HANDLER_PREFIX: &str = "__ts_on_";
pub const GENERATED_FINAL_STATE_MARKER: &str = "__ts_final_state_marker";

pub fn is_generated_state_name(type_name: &str) -> bool {
    type_name.starts_with(GENERATED_STATE_PREFIX)
}

pub fn parse_generated_state_name(type_name: &str) -> Option<(String, String)> {
    let rest = type_name.strip_prefix(GENERATED_STATE_PREFIX)?;
    let (typestate_name, state_name) = rest.rsplit_once('_')?;
    Some((typestate_name.to_string(), state_name.to_string()))
}

pub fn is_generated_handler_name(method_name: &str) -> bool {
    method_name.starts_with(GENERATED_HANDLER_PREFIX)
}

/// Parses a generated handler name to extract the request-site label suffix.
///
/// Generated by typestate lowering:
///   `__ts_on_<ordinal>__site_<label>`
pub fn parse_generated_handler_site_label(method_name: &str) -> Option<&str> {
    let suffix = method_name.strip_prefix(GENERATED_HANDLER_PREFIX)?;
    let (_, label) = suffix.split_once("__site_")?;
    if label.is_empty() {
        return None;
    }
    Some(label)
}

#[cfg(test)]
mod tests {
    use super::{
        is_generated_handler_name, is_generated_state_name, parse_generated_handler_site_label,
        parse_generated_state_name,
    };

    #[test]
    fn parses_generated_state_names() {
        assert_eq!(
            parse_generated_state_name("__ts_Connection_Connected"),
            Some(("Connection".to_string(), "Connected".to_string()))
        );
        assert!(is_generated_state_name("__ts_Connection_Connected"));
        assert!(!is_generated_state_name("Connection"));
    }

    #[test]
    fn parses_generated_handler_names() {
        assert!(is_generated_handler_name("__ts_on_0"));
        assert_eq!(
            parse_generated_handler_site_label("__ts_on_1__site_auth"),
            Some("auth")
        );
        assert_eq!(parse_generated_handler_site_label("__ts_on_1"), None);
    }
}
